services:
  counter:
    image: dmitriynazarov/diplom:test
    build: .
    ports:
      - 80:3002
    environment:
      - PORT=3002     
    depends_on:      
      - mongo
      - mongo-express   
    volumes:
      - ./public/images:/diplom/app/public/images
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - '27017:27017'

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_SERVER: mongo
    depends_on:
      - mongo

   